server {
	# listen for HTTPS traffic on port 443
	listen 443 ssl;

	# the domain name this server block responds to
	server_name diade-so.42.fr;

	# Self-signed Transport Layer Security (TLS) certificate used to encrypt HTTPS traffic
	ssl_certificate /etc/nginx/ssl/server.crt;
	
	# Private key used to authenticate the TLS certificate
	ssl_certificate_key /etc/nginx/ssl/server.key;
	
	# Only allow secure TLS versions required by the project
	ssl_protocols TLSv1.2 TLSv1.3;

	# Allow larger file uploads required by WordPress
	client_max_body_size 64M;

	# Hide nginx version information from HTTP headers
	server_tokens off;

	# Disable directory listings for security
	autoindex off;

	# directory containing the WordPress files
	root /var/www/html;
	
	# default files to look for when accessing a directory
	index index.php index.html;

	location / {
		# Try to serve the requested file/directory.
		# If it does not exist, forward the request to WordPress index.php.
		# $args preserves URL parameters.
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		# Forward PHP requests to the WordPress PHP-FPM container.
		# PHP-FPM listens on port 9000.
		fastcgi_pass wordpress:9000;

		# load default FastCGI parameters requred by PHP-FPM
		include fastcgi_params;

		# Tell PHP-FPM which PHP script should be executed.
		# Combines the document root with the requested PHP file.
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}
