#flow: make up
# -> build images -> create containers -> create network
# -> create volumes -> start containers

# network config:
#   browser talks to nginx
#   nginx talks to wordpress
#   wordpress talks to mariadb

services:

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      # <host volume> : <container path>
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure

  nginx:
    build:
    # Build the image from the local Dockerfile located in
    # ./requirements/nginx and tag the resulting image as "nginx".
    # Because a build context is provided, Docker Compose builds the
    # image locally instead of pulling nginx from Docker Hub.
      context: ./requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - "443:443"
    networks:
      - inception
    # on-failure for development stage
    # change back to unless-stopped after devlopment stage
    # These are persistent services that should recover automatically
    # after crashes or host reboots. Unless I manually stop them,
    # Docker keeps them running
    restart: on-failure

# Docker network for internal communication
# Containers communicate using service names:
# nginx -> wordpress -> mariadb
networks:
  inception:

# Docker named volumes
# Persistent data stored outside containers
# if we remove containers the data is preserved with volumes
#
volumes:
  #give the docker volume a name (named volume)
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      # dont mount a filesystem, mount an existing directory (device)
      o: bind
      # host directory where mariadb is persisted
      device: ${HOME}/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

# Docker secrets
# Sensitive information is stored outside the repository
secrets:

  db_password:
    file: ../secrets/db_password.txt

  db_root_password:
    file: ../secrets/db_root_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_user_password:
    file: ../secrets/wp_user_password.txt
